/**
 * Скелет древа v3 — минимальный хаб + ветка воровства для плейтеста формулы.
 * Полные профессии/зоны переносятся из v2 постепенно.
 */

import type { SkillEdgeV3, SkillNodeV3 } from './types';

export const SKILL_NODES_V3: SkillNodeV3[] = [
  {
    id: 'v3_hub',
    x: 0,
    y: 0,
    label: 'Очаг',
    zone: 'center',
    category: 'root',
    cost: { type: 'OR', amount: 0 },
    description: 'Корень древа v3. Дальше — квели и мастерство.',
  },
  {
    id: 'v3_path_body',
    x: 220,
    y: 80,
    label: 'Путь Тела',
    zone: 'dexterity',
    category: 'transit',
    cost: { type: 'OR', amount: 1 },
    description: 'Дорога к квелям моторики и воровства.',
    requirements: { parentIds: ['v3_hub'] },
  },
  {
    id: 'v3_kvel_theft',
    x: 420,
    y: 40,
    label: 'Квель воровства',
    zone: 'dexterity',
    category: 'kvel',
    cost: { type: 'OR', amount: 2 },
    kvelId: 'theft',
    kvelDelta: 1,
    description: '+1 к Квелю воровства (1→10). Лига карманника/взломщика.',
    requirements: { parentIds: ['v3_path_body'] },
  },
  {
    id: 'v3_kvel_theft_2',
    x: 580,
    y: 40,
    label: 'Квель воровства II',
    zone: 'dexterity',
    category: 'kvel',
    cost: { type: 'OR', amount: 2 },
    kvelId: 'theft',
    kvelDelta: 1,
    description: 'Ещё +1 к Квелю воровства.',
    requirements: {
      parentIds: ['v3_kvel_theft'],
      minKvel: { kvelId: 'theft', rank: 1 },
    },
  },
  {
    id: 'v3_ms_sleight_novice',
    x: 420,
    y: 180,
    label: 'Ловкость рук · новичок',
    zone: 'dexterity',
    category: 'mastery',
    cost: { type: 'OR', amount: 1 },
    masteryKey: 'sleight_of_hand',
    masterySet: 'novice',
    description: 'Ступень «новичок»: на к8 успех с 7+.',
    requirements: { parentIds: ['v3_path_body'] },
  },
  {
    id: 'v3_ms_sleight_apprentice',
    x: 580,
    y: 180,
    label: 'Ловкость рук · ученик',
    zone: 'dexterity',
    category: 'mastery',
    cost: { type: 'OR', amount: 1 },
    masteryKey: 'sleight_of_hand',
    masterySet: 'apprentice',
    description: 'Успех на 6+.',
    requirements: {
      parentIds: ['v3_ms_sleight_novice'],
      minMastery: { key: 'sleight_of_hand', tier: 'novice' },
    },
  },
  {
    id: 'v3_ms_sleight_expert',
    x: 740,
    y: 180,
    label: 'Ловкость рук · эксперт',
    zone: 'dexterity',
    category: 'mastery',
    cost: { type: 'OR', amount: 2 },
    masteryKey: 'sleight_of_hand',
    masterySet: 'expert',
    description: 'Успех на 5+.',
    requirements: {
      parentIds: ['v3_ms_sleight_apprentice'],
      minMastery: { key: 'sleight_of_hand', tier: 'apprentice' },
    },
  },
  {
    id: 'v3_ms_sleight_adept',
    x: 900,
    y: 180,
    label: 'Ловкость рук · адепт',
    zone: 'dexterity',
    category: 'mastery',
    cost: { type: 'OR', amount: 2 },
    masteryKey: 'sleight_of_hand',
    masterySet: 'adept',
    description: 'Успех на 4+.',
    requirements: {
      parentIds: ['v3_ms_sleight_expert'],
      minMastery: { key: 'sleight_of_hand', tier: 'expert' },
    },
  },
  {
    id: 'v3_ms_sleight_master',
    x: 1060,
    y: 180,
    label: 'Ловкость рук · мастер',
    zone: 'dexterity',
    category: 'mastery',
    cost: { type: 'OR', amount: 3 },
    masteryKey: 'sleight_of_hand',
    masterySet: 'master',
    description: 'Успех на 3+. Провал только на 1–2.',
    requirements: {
      parentIds: ['v3_ms_sleight_adept'],
      minMastery: { key: 'sleight_of_hand', tier: 'adept' },
      minKvel: { kvelId: 'theft', rank: 4 },
    },
  },
  {
    id: 'v3_ms_sleight_beast',
    x: 1220,
    y: 180,
    label: 'Ловкость рук · зверь',
    zone: 'dexterity',
    category: 'mastery',
    cost: { type: 'OR', amount: 5 },
    masteryKey: 'sleight_of_hand',
    masterySet: 'beast',
    description: 'Провала нет. Кэпстоун.',
    requirements: {
      parentIds: ['v3_ms_sleight_master'],
      minMastery: { key: 'sleight_of_hand', tier: 'master' },
      minKvel: { kvelId: 'theft', rank: 7 },
    },
  },
  {
    id: 'v3_char_motor_novice',
    x: 420,
    y: 320,
    label: 'Моторика · новичок',
    zone: 'dexterity',
    category: 'mastery',
    cost: { type: 'OR', amount: 1 },
    masteryKey: 'motorika',
    masterySet: 'novice',
    description: 'Широкая характеристика. Не заменяет Ловкость рук в узком споре.',
    requirements: { parentIds: ['v3_path_body'] },
  },
];

export const SKILL_EDGES_V3: SkillEdgeV3[] = [
  { from: 'v3_hub', to: 'v3_path_body' },
  { from: 'v3_path_body', to: 'v3_kvel_theft' },
  { from: 'v3_kvel_theft', to: 'v3_kvel_theft_2' },
  { from: 'v3_path_body', to: 'v3_ms_sleight_novice' },
  { from: 'v3_ms_sleight_novice', to: 'v3_ms_sleight_apprentice' },
  { from: 'v3_ms_sleight_apprentice', to: 'v3_ms_sleight_expert' },
  { from: 'v3_ms_sleight_expert', to: 'v3_ms_sleight_adept' },
  { from: 'v3_ms_sleight_adept', to: 'v3_ms_sleight_master' },
  { from: 'v3_ms_sleight_master', to: 'v3_ms_sleight_beast' },
  { from: 'v3_path_body', to: 'v3_char_motor_novice' },
];
